export interface LocalizationStrings {
  LANG_CODE: string;
  EMAIL_TITLE: string;
  GAME_SUBTITLE: string;
  THANK_YOU_MESSAGE: string;
  MAIN_MESSAGE: string;
  DATE_LABEL: string;
  REQUEST_ID_LABEL: string;
  YOUR_MESSAGE_LABEL: string;
  NO_REPLY_MESSAGE: string;
  KEEP_PLAYING: string;
  AUTOMATED_MESSAGE: string;
}

const localizations: Record<string, LocalizationStrings> = {
  en: {
    LANG_CODE: 'en',
    EMAIL_TITLE: 'Block Royale - Thank you for your message!',
    GAME_SUBTITLE: 'Epic Block Puzzle Game',
    THANK_YOU_MESSAGE: 'Thank you for your message!',
    MAIN_MESSAGE: 'We have received your request and greatly appreciate that you took the time to contact us. Our Block Royale team is already working on your request and will get back to you shortly.',
    DATE_LABEL: 'Submission Date',
    REQUEST_ID_LABEL: 'Request ID',
    YOUR_MESSAGE_LABEL: 'Your Message',
    NO_REPLY_MESSAGE: 'Please do not reply to this email. Our team will contact you at the provided email address.',
    KEEP_PLAYING: 'Keep playing Block Royale!',
    AUTOMATED_MESSAGE: 'This is an automated message generated by Block Royale support system'
  },
  
  ru: {
    LANG_CODE: 'ru',
    EMAIL_TITLE: 'Block Royale - Спасибо за ваше сообщение!',
    GAME_SUBTITLE: 'Эпичная игра-пазл',
    THANK_YOU_MESSAGE: 'Спасибо за ваше сообщение!',
    MAIN_MESSAGE: 'Мы получили ваше обращение и очень ценим, что вы нашли время связаться с нами. Наша команда Block Royale уже работает над вашим запросом и свяжется с вами в ближайшее время.',
    DATE_LABEL: 'Дата отправки',
    REQUEST_ID_LABEL: 'ID обращения',
    YOUR_MESSAGE_LABEL: 'Ваше сообщение',
    NO_REPLY_MESSAGE: 'Пожалуйста, не отвечайте на это письмо. Наша команда свяжется с вами по указанному адресу электронной почты.',
    KEEP_PLAYING: 'Продолжайте играть в Block Royale!',
    AUTOMATED_MESSAGE: 'Это автоматическое сообщение, созданное системой поддержки Block Royale'
  },
  
  uk: {
    LANG_CODE: 'uk',
    EMAIL_TITLE: 'Block Royale - Дякуємо за ваше повідомлення!',
    GAME_SUBTITLE: 'Епічна гра-пазл з блоками',
    THANK_YOU_MESSAGE: 'Дякуємо за ваше повідомлення!',
    MAIN_MESSAGE: 'Ми отримали ваше звернення і дуже цінуємо, що ви знайшли час зв\'язатися з нами. Наша команда Block Royale вже працює над вашим запитом і незабаром з вами зв\'яжеться.',
    DATE_LABEL: 'Дата відправлення',
    REQUEST_ID_LABEL: 'ID звернення',
    YOUR_MESSAGE_LABEL: 'Ваше повідомлення',
    NO_REPLY_MESSAGE: 'Будь ласка, не відповідайте на цей лист. Наша команда зв\'яжеться з вами за вказаною електронною адресою.',
    KEEP_PLAYING: 'Продовжуйте грати в Block Royale!',
    AUTOMATED_MESSAGE: 'Це автоматичне повідомлення, створене системою підтримки Block Royale'
  },
  
  fr: {
    LANG_CODE: 'fr',
    EMAIL_TITLE: 'Block Royale - Merci pour votre message!',
    GAME_SUBTITLE: 'Jeu de Puzzle Épique',
    THANK_YOU_MESSAGE: 'Merci pour votre message!',
    MAIN_MESSAGE: 'Nous avons reçu votre demande et apprécions grandement que vous ayez pris le temps de nous contacter. Notre équipe Block Royale travaille déjà sur votre demande et vous recontactera sous peu.',
    DATE_LABEL: 'Date de soumission',
    REQUEST_ID_LABEL: 'ID de demande',
    YOUR_MESSAGE_LABEL: 'Votre Message',
    NO_REPLY_MESSAGE: 'Veuillez ne pas répondre à cet email. Notre équipe vous contactera à l\'adresse email fournie.',
    KEEP_PLAYING: 'Continuez à jouer à Block Royale!',
    AUTOMATED_MESSAGE: 'Ceci est un message automatique généré par le système de support Block Royale'
  },
  
  pl: {
    LANG_CODE: 'pl',
    EMAIL_TITLE: 'Block Royale - Dziękujemy za wiadomość!',
    GAME_SUBTITLE: 'Epiczna Gra Puzzle',
    THANK_YOU_MESSAGE: 'Dziękujemy za wiadomość!',
    MAIN_MESSAGE: 'Otrzymaliśmy Twoje zgłoszenie i bardzo cenimy, że znalazłeś czas, aby się z nami skontaktować. Nasz zespół Block Royale już pracuje nad Twoim zapytaniem i wkrótce się z Tobą skontaktuje.',
    DATE_LABEL: 'Data wysłania',
    REQUEST_ID_LABEL: 'ID zgłoszenia',
    YOUR_MESSAGE_LABEL: 'Twoja wiadomość',
    NO_REPLY_MESSAGE: 'Proszę nie odpowiadaj na ten email. Nasz zespół skontaktuje się z Tobą pod podanym adresem email.',
    KEEP_PLAYING: 'Kontynuuj grę w Block Royale!',
    AUTOMATED_MESSAGE: 'To jest automatyczna wiadomość wygenerowana przez system wsparcia Block Royale'
  },
  
  it: {
    LANG_CODE: 'it',
    EMAIL_TITLE: 'Block Royale - Grazie per il tuo messaggio!',
    GAME_SUBTITLE: 'Gioco di Puzzle Epico',
    THANK_YOU_MESSAGE: 'Grazie per il tuo messaggio!',
    MAIN_MESSAGE: 'Abbiamo ricevuto la tua richiesta e apprezziamo molto che tu abbia dedicato del tempo per contattarci. Il nostro team di Block Royale sta già lavorando sulla tua richiesta e ti ricontatterà a breve.',
    DATE_LABEL: 'Data di Invio',
    REQUEST_ID_LABEL: 'ID Richiesta',
    YOUR_MESSAGE_LABEL: 'Il Tuo Messaggio',
    NO_REPLY_MESSAGE: 'Si prega di non rispondere a questa email. Il nostro team ti contatterà all\'indirizzo email fornito.',
    KEEP_PLAYING: 'Continua a giocare a Block Royale!',
    AUTOMATED_MESSAGE: 'Questo è un messaggio automatico generato dal sistema di supporto Block Royale'
  },
  
  tr: {
    LANG_CODE: 'tr',
    EMAIL_TITLE: 'Block Royale - Mesajınız için teşekkürler!',
    GAME_SUBTITLE: 'Destansı Blok Bulmaca Oyunu',
    THANK_YOU_MESSAGE: 'Mesajınız için teşekkürler!',
    MAIN_MESSAGE: 'Talebinizi aldık ve bizimle iletişime geçmek için zaman ayırdığınız için çok memnunuz. Block Royale ekibimiz zaten talebiniz üzerinde çalışıyor ve kısa süre içinde size geri dönecek.',
    DATE_LABEL: 'Gönderim Tarihi',
    REQUEST_ID_LABEL: 'Talep Kimliği',
    YOUR_MESSAGE_LABEL: 'Mesajınız',
    NO_REPLY_MESSAGE: 'Lütfen bu e-postayı yanıtlamayın. Ekibimiz size verilen e-posta adresinden ulaşacaktır.',
    KEEP_PLAYING: 'Block Royale oynamaya devam edin!',
    AUTOMATED_MESSAGE: 'Bu, Block Royale destek sistemi tarafından oluşturulan otomatik bir mesajdır'
  },
  
  de: {
    LANG_CODE: 'de',
    EMAIL_TITLE: 'Block Royale - Vielen Dank für Ihre Nachricht!',
    GAME_SUBTITLE: 'Episches Block-Puzzle-Spiel',
    THANK_YOU_MESSAGE: 'Vielen Dank für Ihre Nachricht!',
    MAIN_MESSAGE: 'Wir haben Ihre Anfrage erhalten und schätzen es sehr, dass Sie sich die Zeit genommen haben, uns zu kontaktieren. Unser Block Royale-Team arbeitet bereits an Ihrer Anfrage und wird sich in Kürze bei Ihnen melden.',
    DATE_LABEL: 'Übermittlungsdatum',
    REQUEST_ID_LABEL: 'Anfrage-ID',
    YOUR_MESSAGE_LABEL: 'Ihre Nachricht',
    NO_REPLY_MESSAGE: 'Bitte antworten Sie nicht auf diese E-Mail. Unser Team wird Sie unter der angegebenen E-Mail-Adresse kontaktieren.',
    KEEP_PLAYING: 'Spielen Sie weiterhin Block Royale!',
    AUTOMATED_MESSAGE: 'Dies ist eine automatische Nachricht, die vom Block Royale-Support-System generiert wurde'
  },
  
  es: {
    LANG_CODE: 'es',
    EMAIL_TITLE: 'Block Royale - ¡Gracias por tu mensaje!',
    GAME_SUBTITLE: 'Juego de Rompecabezas Épico',
    THANK_YOU_MESSAGE: '¡Gracias por tu mensaje!',
    MAIN_MESSAGE: 'Hemos recibido tu solicitud y apreciamos mucho que hayas dedicado tiempo para contactarnos. Nuestro equipo de Block Royale ya está trabajando en tu solicitud y te contactará en breve.',
    DATE_LABEL: 'Fecha de Envío',
    REQUEST_ID_LABEL: 'ID de Solicitud',
    YOUR_MESSAGE_LABEL: 'Tu Mensaje',
    NO_REPLY_MESSAGE: 'Por favor no respondas a este correo. Nuestro equipo te contactará en la dirección de correo proporcionada.',
    KEEP_PLAYING: '¡Sigue jugando Block Royale!',
    AUTOMATED_MESSAGE: 'Este es un mensaje automático generado por el sistema de soporte de Block Royale'
  }
};

export function getLocalization(language: string): LocalizationStrings {
  const supportedLanguages = ['en', 'uk', 'ru', 'fr', 'pl', 'it', 'tr', 'de', 'es'];
  const lang = supportedLanguages.includes(language) ? language : 'en';
  return localizations[lang];
}

export function getSupportedLanguages(): string[] {
  return Object.keys(localizations);
}